"""Runner for why-did-you-render — patches React to log avoidable re-renders."""

from __future__ import annotations

import json

from viberapid.models import ToolResult, ToolStatus
from viberapid.normalisers.why_did_you_render import WhyDidYouRenderNormaliser
from viberapid.runners.base import AsyncToolRunner


class WhyDidYouRenderRunner(AsyncToolRunner):
    """Analyse why-did-you-render log output to identify avoidable React re-renders.

    why-did-you-render (WDYR) is a React instrumentation library that patches
    React.createElement to detect and log unnecessary re-renders. It outputs
    detailed information about what changed and why each re-render occurred.

    This runner reads WDYR output from either:
    1. A log file generated by the instrumented app (tools.why-did-you-render.log_file)
    2. stdout from running a test suite with WDYR enabled
    """

    name = "why-did-you-render"
    requires_node = True

    def should_run(self) -> bool:
        if not self._file_exists("package.json"):
            self.skip_reason = "no package.json found"
            return False

        log_file = self.tool_config.get("log_file")
        test_cmd = self.tool_config.get("test_command")

        if not log_file and not test_cmd:
            # Check if WDYR is installed
            has_wdyr = self._check_wdyr_dependency()
            if not has_wdyr:
                self.skip_reason = (
                    "why-did-you-render not found in dependencies — install it or "
                    "set tools.why-did-you-render.log_file in .viberapid.yml"
                )
                return False

            # Check for a WDYR setup file
            wdyr_files = self._glob_files(
                "**/wdyr.js", "**/wdyr.ts", "**/wdyr.tsx",
                "**/whyDidYouRender.js", "**/whyDidYouRender.ts",
            )
            if not wdyr_files:
                self.skip_reason = (
                    "no WDYR setup file found (wdyr.js/ts) — configure WDYR in your "
                    "project or set tools.why-did-you-render.log_file"
                )
                return False

        if log_file:
            from pathlib import Path
            log_path = Path(self.target) / log_file
            if not log_path.exists():
                self.skip_reason = f"WDYR log file not found: {log_file}"
                return False

        return True

    def run(self, changed_files: list[str] | None = None) -> ToolResult:
        log_file = self.tool_config.get("log_file")
        test_cmd = self.tool_config.get("test_command")

        data = None

        if log_file:
            # Read from existing log file
            data = self._read_log_file(log_file)
        elif test_cmd:
            # Run a test command that exercises WDYR-instrumented components
            data = self._run_test_command(test_cmd)
        else:
            # Try to run a standard test command with WDYR enabled
            data = self._run_default_test()

        if data is None:
            return self._make_error_result(
                "why-did-you-render produced no parseable output. Ensure WDYR is "
                "configured and the application exercises the instrumented components."
            )

        normaliser = WhyDidYouRenderNormaliser()
        findings = normaliser.normalise(data)

        total_rerenders = 0
        if isinstance(data, dict):
            entries = data.get("entries", [])
            if isinstance(entries, list):
                total_rerenders = len(entries)

        return ToolResult(
            tool=self.name,
            status=ToolStatus.SUCCESS,
            findings=findings,
            metrics={
                "total_rerender_events": total_rerenders,
                "issues_found": len(findings),
                "source": "log_file" if log_file else "test_command",
            },
        )

    def _check_wdyr_dependency(self) -> bool:
        """Check if why-did-you-render is in package.json dependencies."""
        from pathlib import Path
        pkg_path = Path(self.target) / "package.json"
        if not pkg_path.exists():
            return False
        try:
            with open(pkg_path) as f:
                pkg = json.load(f)
            all_deps = {}
            for key in ("dependencies", "devDependencies", "peerDependencies"):
                deps = pkg.get(key, {})
                if isinstance(deps, dict):
                    all_deps.update(deps)
            return "@welldone-software/why-did-you-render" in all_deps
        except (json.JSONDecodeError, OSError):
            return False

    def _read_log_file(self, log_file: str) -> dict | None:
        """Read and parse a WDYR log file."""
        from pathlib import Path
        log_path = Path(self.target) / log_file
        if not log_path.exists():
            return None

        try:
            text = log_path.read_text(errors="replace")
        except OSError:
            return None

        # Try JSON first (structured log)
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            pass

        # Parse text log
        return self._parse_wdyr_log(text)

    def _run_test_command(self, test_cmd: str) -> dict | None:
        """Run a custom test command and capture WDYR output."""
        import shlex

        parts = shlex.split(test_cmd)
        try:
            result = self._exec(parts, timeout=120, env={"WDYR_ENABLED": "true"})
        except Exception:
            return None

        combined = (result.stdout or "") + "\n" + (result.stderr or "")
        return self._parse_wdyr_log(combined)

    def _run_default_test(self) -> dict | None:
        """Try running standard test commands with WDYR."""
        npx = self._npx_path()

        for cmd_parts in [
            [npx, "react-scripts", "test", "--watchAll=false", "--verbose"],
            [npx, "vitest", "run", "--reporter=verbose"],
            [npx, "jest", "--verbose"],
        ]:
            try:
                result = self._exec(
                    cmd_parts, timeout=120, env={"WDYR_ENABLED": "true"}
                )
                combined = (result.stdout or "") + "\n" + (result.stderr or "")
                data = self._parse_wdyr_log(combined)
                if data:
                    return data
            except Exception:
                continue

        return None

    def _parse_wdyr_log(self, text: str) -> dict | None:
        """Parse WDYR console output into structured data.

        WDYR logs look like:
        [why-did-you-render] Dashboard re-rendered because of
          props: {onClick: ƒ onClick}  (prev: ƒ onClick)
          Different keys: onClick
          Old value: ƒ onClick
          New value: ƒ onClick

        Or:
        [WDYR] Component: Dashboard
          Reason: props changed
          Changed props: onClick, items
          File: src/components/Dashboard.tsx
        """
        if not text:
            return None

        entries: list[dict] = []
        current: dict | None = None

        for line in text.splitlines():
            stripped = line.strip()
            if not stripped:
                if current:
                    entries.append(current)
                    current = None
                continue

            lower = stripped.lower()

            # Detect start of a new WDYR entry
            is_wdyr_line = (
                "[why-did-you-render]" in stripped
                or "[wdyr]" in stripped
                or "re-rendered" in lower
            )

            if is_wdyr_line and "re-render" in lower:
                if current:
                    entries.append(current)

                # Extract component name
                component = _extract_component_name(stripped)
                current = {
                    "component": component,
                    "file": "<unknown>",
                    "reason": "",
                    "changed_props": [],
                    "details": [],
                }

            elif current:
                if lower.startswith("props:") or "props changed" in lower:
                    current["reason"] = "props changed"
                    props = _extract_props(stripped)
                    if props:
                        current["changed_props"].extend(props)
                elif lower.startswith("state:") or "state changed" in lower:
                    current["reason"] = "state changed"
                elif lower.startswith("hooks changed") or "hook" in lower:
                    current["reason"] = "hooks changed"
                elif "different keys:" in lower or "changed props:" in lower:
                    props = _extract_props(stripped)
                    if props:
                        current["changed_props"].extend(props)
                elif lower.startswith("file:") or lower.startswith("component:"):
                    value = stripped.split(":", 1)[-1].strip()
                    if lower.startswith("file:"):
                        current["file"] = value
                    elif lower.startswith("component:"):
                        current["component"] = value
                elif stripped:
                    current["details"].append(stripped)

        if current:
            entries.append(current)

        if not entries:
            return None

        return {"entries": entries}


def _extract_component_name(line: str) -> str:
    """Extract component name from a WDYR log line."""
    import re
    # "[why-did-you-render] Dashboard re-rendered..."
    match = re.search(r"\]\s*(\w+)\s+re-render", line)
    if match:
        return match.group(1)

    # "Component: Dashboard"
    match = re.search(r"[Cc]omponent:?\s*(\w+)", line)
    if match:
        return match.group(1)

    return "<Unknown>"


def _extract_props(line: str) -> list[str]:
    """Extract prop names from a WDYR log line."""
    import re
    # "Different keys: onClick, items" or "Changed props: onClick, items"
    match = re.search(r"(?:keys|props|changed):\s*(.+)", line, re.IGNORECASE)
    if match:
        raw = match.group(1)
        # Split on commas and clean up
        return [p.strip().strip("{}") for p in raw.split(",") if p.strip()]

    # "props: {onClick: f}" pattern
    match = re.search(r"props:\s*\{(.+?)\}", line)
    if match:
        inner = match.group(1)
        return [p.split(":")[0].strip() for p in inner.split(",") if p.strip()]

    return []
