"""GitHub-flavored Markdown reporter."""

from __future__ import annotations

from pathlib import Path

from rich.console import Console

from vibeaudit.models import Finding, ScanResult, Severity
from vibeaudit.reporters.base import Reporter

# Severity emoji for markdown
_SEVERITY_EMOJI: dict[Severity, str] = {
    Severity.CRITICAL: "🔴",
    Severity.HIGH: "🟠",
    Severity.MEDIUM: "🟡",
    Severity.LOW: "🔵",
    Severity.INFO: "⚪",
}


class MarkdownReporter(Reporter):
    """Outputs a GitHub-flavored Markdown security report."""

    def report(self, result: ScanResult, console: Console, output_path: Path | None = None) -> None:
        lines: list[str] = []

        # Title
        lines.append("# vibeaudit Security Report")
        lines.append("")
        lines.append(f"> Generated: {result.timestamp.strftime('%Y-%m-%d %H:%M:%S UTC')}")
        if result.provider:
            lines.append(f"> Provider: {result.provider} ({result.model})")
        lines.append("")

        # Summary table
        lines.append("## Summary")
        lines.append("")
        lines.append("| Severity | Count |")
        lines.append("|----------|-------|")
        for sev in Severity:
            count = result.counts_by_severity.get(sev.value, 0)
            emoji = _SEVERITY_EMOJI.get(sev, "")
            lines.append(f"| {emoji} {sev.value.upper()} | {count} |")
        total = len(result.findings)
        lines.append(f"| **Total** | **{total}** |")
        lines.append("")

        # Scan metadata
        lines.append("## Scan Details")
        lines.append("")
        lines.append(f"- **Files scanned:** {result.scanned_files}")
        if result.scanned_classes:
            lines.append(f"- **Vulnerability classes:** {len(result.scanned_classes)}")
        if result.total_tokens > 0:
            lines.append(f"- **Tokens used:** {result.total_tokens:,}")
        if result.total_cost_usd > 0:
            lines.append(f"- **Cost:** ${result.total_cost_usd:.2f}")
        if result.duration_seconds > 0:
            lines.append(f"- **Duration:** {result.duration_seconds:.1f}s")
        lines.append("")

        if not result.findings:
            lines.append("**No security findings detected.**")
            lines.append("")
        else:
            # Group findings by severity
            for sev in Severity:
                sev_findings = [f for f in result.findings if f.severity == sev]
                if not sev_findings:
                    continue

                emoji = _SEVERITY_EMOJI.get(sev, "")
                lines.append(f"## {emoji} {sev.value.upper()} Findings ({len(sev_findings)})")
                lines.append("")

                for finding in sev_findings:
                    self._render_finding(finding, lines)

        # Footer
        lines.append("---")
        lines.append("")
        lines.append("*Generated by [vibeaudit](https://github.com/vibeaudit/vibeaudit) v0.1.0*")
        lines.append("")

        content = "\n".join(lines)

        if output_path:
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(content, encoding="utf-8")
            console.print(f"[green]Markdown report written to {output_path}[/green]")
        else:
            console.print(content, highlight=False)

    def _render_finding(self, finding: Finding, lines: list[str]) -> None:
        """Render a single finding as markdown."""
        lines.append(f"### {finding.title}")
        lines.append("")
        lines.append(f"- **ID:** `{finding.id}`")
        lines.append(f"- **Class:** {finding.vuln_class.value}")
        lines.append(f"- **Confidence:** {finding.confidence.value}")
        lines.append(f"- **File:** `{finding.file_location}`")
        if finding.cwe_id:
            lines.append(f"- **CWE:** {finding.cwe_id}")
        if finding.owasp_category:
            lines.append(f"- **OWASP:** {finding.owasp_category}")
        lines.append("")

        if finding.description:
            lines.append("**Description:**")
            lines.append("")
            lines.append(finding.description)
            lines.append("")

        if finding.attack_scenario:
            lines.append("**Attack Scenario:**")
            lines.append("")
            lines.append(finding.attack_scenario)
            lines.append("")

        if finding.impact:
            lines.append("**Impact:**")
            lines.append("")
            lines.append(finding.impact)
            lines.append("")

        if finding.remediation:
            lines.append("**Remediation:**")
            lines.append("")
            lines.append(finding.remediation)
            lines.append("")

        if finding.fix_example:
            lines.append("**Fix Example:**")
            lines.append("")
            lang = finding.snippets[0].language if finding.snippets else ""
            lines.append(f"```{lang}")
            lines.append(finding.fix_example)
            lines.append("```")
            lines.append("")

        if finding.snippets:
            lines.append("**Affected Code:**")
            lines.append("")
            for snippet in finding.snippets:
                lang = snippet.language if snippet.language != "unknown" else ""
                lines.append(f"`{snippet.file_path}:{snippet.start_line}-{snippet.end_line}`")
                lines.append("")
                lines.append(f"```{lang}")
                lines.append(snippet.content)
                lines.append("```")
                lines.append("")

        lines.append("---")
        lines.append("")
