"""Markdown reporter — PR comment format with checklist."""

from __future__ import annotations

from rich.console import Console

from vibedeploy.models import Finding, Severity
from vibedeploy.reporters.base import BaseReporter

_SEVERITY_EMOJI = {
    Severity.CRITICAL: "\U0001f534",
    Severity.HIGH: "\U0001f7e0",
    Severity.MEDIUM: "\U0001f7e1",
    Severity.LOW: "\U0001f535",
    Severity.INFO: "\u26aa",
}


def _location(f: Finding) -> str:
    loc = f"`{f.file}"
    if f.line is not None:
        loc += f":{f.line}"
    loc += "`"
    return loc


class MarkdownReporter(BaseReporter):
    """GitHub-flavored markdown report."""

    def render(self, console: Console) -> None:
        console.print(self.render_to_string())

    def render_to_string(self) -> str:
        lines: list[str] = []
        result = self.result
        score = result.readiness_score
        blockers = len(result.deploy_blockers)

        # Header
        passed = result.exit_code == 0
        icon = "\u2705" if passed else "\u274c"
        lines.append(f"## {icon} vibedeploy — Deploy Readiness: {score}/100")
        lines.append("")

        # Summary
        lines.append(f"**Target**: `{result.target}`")
        lines.append(f"**Deploy Blockers**: {blockers}")
        lines.append("")

        # Severity table
        lines.append("| Severity | Count |")
        lines.append("|----------|-------|")
        for sev in (Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO):
            count = result.severity_counts.get(sev.value, 0)
            emoji = _SEVERITY_EMOJI[sev]
            lines.append(f"| {emoji} {sev.value} | {count} |")
        lines.append("")

        # Deploy blockers
        if result.deploy_blockers:
            lines.append("### Deploy Blockers")
            lines.append("")
            for f in result.deploy_blockers:
                loc = _location(f)
                lines.append(f"- [ ] **[{f.tool}]** {f.message[:120]}")
                lines.append(f"  - {loc}")
                if f.fix_hint:
                    lines.append(f"  - Fix: {f.fix_hint}")
            lines.append("")

        # Top findings (non-blockers)
        non_blockers = [
            f for f in result.deduplicated_findings
            if not f.blocks_deploy
        ][:10]

        if non_blockers:
            lines.append("### Top Findings")
            lines.append("")
            lines.append("| Severity | Tool | Location | Message |")
            lines.append("|----------|------|----------|---------|")
            for f in non_blockers:
                sev = f"{_SEVERITY_EMOJI[f.severity]} {f.severity.value}"
                loc = _location(f)
                msg = f.message[:80]
                if len(f.message) > 80:
                    msg += "..."
                lines.append(f"| {sev} | {f.tool} | {loc} | {msg} |")
            lines.append("")

        # Tool status
        lines.append("<details>")
        lines.append("<summary>Tool Status</summary>")
        lines.append("")
        lines.append("| Tool | Status | Findings | Duration |")
        lines.append("|------|--------|----------|----------|")
        for tr in result.tool_results:
            icon = "\u2713" if tr.status.value in ("success", "partial") else "\u2717"
            lines.append(
                f"| {tr.tool} | {icon} {tr.status.value} | {len(tr.findings)} | {tr.duration_seconds:.1f}s |"
            )
        lines.append("")
        lines.append("</details>")
        lines.append("")

        lines.append("---")
        lines.append("*Generated by [vibedeploy](https://github.com/vibedeploy/vibedeploy)*")

        return "\n".join(lines)
