"""Markdown reporter — PR comment format (GitHub-flavored markdown)."""

from __future__ import annotations

from rich.console import Console
from rich.markdown import Markdown

from vibetest.config import Config
from vibetest.models import Category, Finding, ScanResult, Severity, RunnerStatus
from vibetest.reporters.base import BaseReporter

_MAX_FINDINGS = 15

_SEVERITY_EMOJI: dict[Severity, str] = {
    Severity.CRITICAL: "\U0001f534",
    Severity.HIGH: "\U0001f7e0",
    Severity.MEDIUM: "\U0001f7e1",
    Severity.LOW: "\U0001f535",
    Severity.INFO: "\u26aa",
}

_STATUS_ICON: dict[RunnerStatus, str] = {
    RunnerStatus.SUCCESS: "\u2705",
    RunnerStatus.PARTIAL: "\u26a0\ufe0f",
    RunnerStatus.FAILED: "\u274c",
    RunnerStatus.SKIPPED: "\u23ed\ufe0f",
}


class MarkdownReporter(BaseReporter):
    """Concise markdown report designed for PR comments."""

    def __init__(self, result: ScanResult, config: Config):
        super().__init__(result, config)

    def render(self, console: Console) -> None:
        md_str = self.render_to_string()
        console.print(Markdown(md_str))

    def render_to_string(self) -> str:
        lines: list[str] = []
        self._write_header(lines)
        self._write_severity_table(lines)
        self._write_top_findings(lines)
        self._write_runner_status(lines)
        self._write_footer(lines)
        return "\n".join(lines)

    def _write_header(self, lines: list[str]) -> None:
        total = len(self.result.findings)
        status = "PASS" if self.result.exit_code == 0 else "FAIL"
        icon = "\u2705" if self.result.exit_code == 0 else "\u274c"

        lines.append(f"## {icon} vibetest: {status}")
        lines.append("")
        lines.append(
            f"> **{total}** finding{'s' if total != 1 else ''} "
            f"in **{self.result.duration_seconds:.1f}s** "
            f"| target: `{self.result.target}` "
            f"| exit: `{self.result.exit_code}`"
        )
        lines.append("")

    def _write_severity_table(self, lines: list[str]) -> None:
        counts = self.result.severity_counts

        lines.append("### Severity Summary")
        lines.append("")
        lines.append("| Severity | Count |")
        lines.append("|----------|------:|")

        for sev in (Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO):
            count = counts.get(sev.value, 0)
            emoji = _SEVERITY_EMOJI[sev]
            lines.append(f"| {emoji} {sev.value} | {count} |")

        lines.append("")

    def _write_top_findings(self, lines: list[str]) -> None:
        findings = sorted(
            self.result.findings,
            key=lambda f: f.severity.rank,
            reverse=True,
        )[:_MAX_FINDINGS]

        if not findings:
            lines.append("*No findings detected.*")
            lines.append("")
            return

        total = len(self.result.findings)
        shown = len(findings)
        title = f"### Top {shown} Findings"
        if total > shown:
            title += f" (of {total})"
        lines.append(title)
        lines.append("")
        lines.append("| Severity | Category | Runner | Location | Message |")
        lines.append("|----------|----------|--------|----------|---------|")

        for f in findings:
            emoji = _SEVERITY_EMOJI[f.severity]
            loc = f"`{f.file}"
            if f.line is not None:
                loc += f":{f.line}"
            loc += "`"
            msg = f.message.replace("|", "\\|")
            if len(msg) > 100:
                msg = msg[:97] + "..."
            lines.append(f"| {emoji} {f.severity.value} | {f.category.value} | {f.runner} | {loc} | {msg} |")

        lines.append("")

    def _write_runner_status(self, lines: list[str]) -> None:
        lines.append("<details>")
        lines.append("<summary><strong>Runner Status</strong></summary>")
        lines.append("")
        lines.append("| Runner | Status | Findings | Duration |")
        lines.append("|--------|--------|----------|----------|")

        for rr in self.result.runner_results:
            icon = _STATUS_ICON.get(rr.status, "?")
            finding_count = len(rr.findings)
            duration = f"{rr.duration_seconds:.1f}s"
            error_note = f" ({rr.error})" if rr.error else ""
            lines.append(
                f"| `{rr.runner}` | {icon} {rr.status.value}{error_note} "
                f"| {finding_count} | {duration} |"
            )

        lines.append("")
        lines.append("</details>")
        lines.append("")

    def _write_footer(self, lines: list[str]) -> None:
        lines.append("---")
        lines.append(
            "*Generated by [vibetest](https://github.com/vibetest/vibetest)*"
        )
        lines.append("")
